name: Deploy Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, curl, json, openssl
          tools: composer

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            if [ ! -d /var/www/html/my.thehustlelab.io/public_html/api/.git ]; then
              git clone https://github.com/ZodicSlanser/joke-backend.git /var/www/html/my.thehustlelab.io/public_html/api
            else
              cd /var/www/html/my.thehustlelab.io/public_html/api
              git pull origin main
            fi
            cd /var/www/html/my.thehustlelab.io/public_html/api
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan serve --host=0.0.0.0 --port=8000 &
